//-- #arquivo:tests/tests.rest
//-- #testede API/

GET http://localhost:40000/ HTTP/1.1
content-type: application/json

###

//-- #testede APIhelloUserGet
GET http://localhost:40000/helloUserGet/"John Doe" HTTP/1.1

###
//-- #testede APIhelloUserPost
POST http://localhost:40000/helloUserPost HTTP/1.1
content-type: application/json

{
"username": "JohnDoe"
}
